title: $ /bin/Grizzz
author: Grizzz
email: nguyenngocquang700@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Nếu ngày mai không đến...anh xin nói một lời yêu em...yêu say đắm như lần đầu tiên...
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 1
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: nguyenngocquang700.github.io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/Quangng20/
      icon: twitter-square
      color: cyan
    - url: https://github.com/nguyenngocquang700/
      icon: github-square
      color: purple
    - url: https://facebook.com/qng20/
      icon: facebook-square
      color: blue
    - url: https://instagram.com/hello.wangg/
      icon: instagram-square
      color: pink

  show_author: true

  animation_speed: 50

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
avatar_source: github
github_username: nguyenngocquang700
